/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package edu.pe.ulima.frontend.pideya.desktop.internalframe;

import java.awt.Color;
import java.awt.Font;
import java.net.URL;
import javax.swing.ImageIcon;

/**
 *
 * @author hwong
 */
public class FrmAcercaDe extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmAcercaDe
     */
    public FrmAcercaDe() {
        initComponents();
        URL url = getClass().getClassLoader().getResource("Logo.png");
        if (url != null) {
            lblTituloFormulario.setIcon(new ImageIcon(url));
        } else {
            System.err.println("¡Recurso no encontrado: miIcono.png!");
        }
        lblTituloFormulario.setText("Acerca de PideYa");
        setTitle("Acerca de PideYa");

        lblAcerca.setName("lblAcerca");
        lblAcerca.setText(
                "<html>"
                + "<b>Creador:</b> Henry Wong<br>"
                + "<b>Correo:</b> hwong@ulima.edu.pe<br>"
                + "<b>Sistema:</b> PideYa – gestión de pedidos y compras<br>"
                + "<b>Tablas:</b><br>"
                + "&#8226; Categoria<br>"
                + "&#8226; Producto<br>"
                + "&#8226; ClienteNatural<br>"
                + "&#8226; ClienteEmpresa<br>"
                + "&#8226; Usuario<br>"
                + "&#8226; Pedido<br>"
                + "&#8226; DetallePedido<br>"
                + "&#8226; Compra<br>"
                + "<hr style='border:none;border-top:1px solid #CCC;margin:4px 0;'/>"
                + "<span style='font-size:9px;'>"
                + "© 2025 Henry Wong. Este trabajo está bajo licencia "
                + "<a href='https://creativecommons.org/licenses/by/4.0/'>"
                + "Creative Commons Attribution 4.0 International (CC BY 4.0)"
                + "</a>."
                + "</span>"
                + "</html>"
        );

        lblAcerca.setFont(new Font("Segoe UI", Font.PLAIN, 16));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTituloFormulario = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblAcerca = new javax.swing.JLabel();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(589, 60));

        lblTituloFormulario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloFormulario.setText("Mantenimiento");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloFormulario, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloFormulario)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        lblAcerca.setText("jLabel2");
        lblAcerca.setToolTipText("");
        lblAcerca.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAcerca, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAcerca, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAcerca;
    private javax.swing.JLabel lblTituloFormulario;
    // End of variables declaration//GEN-END:variables
}
